package components

import (
	cfg "github.com/automoto/doomerang-mp/config"
	"github.com/yohamta/donburi"
)

// BotStateID represents the bot's current AI state
type BotStateID int

const (
	BotStateIdle BotStateID = iota
	BotStateChase
	BotStateAttack
	BotStateRetreat
)

// BotData stores AI state for bot-controlled players.
// When a player entity has this component, its inputs are generated by AI.
type BotData struct {
	Difficulty cfg.BotDifficulty
	AIState    BotStateID

	// Target tracking
	TargetPlayerIndex int     // Index of player being targeted (-1 = none)
	TargetX           float64 // Last known target X position
	TargetY           float64 // Last known target Y position
	DistanceToTarget  float64

	// Timers
	DecisionTimer  int // Frames until next AI decision (adds reaction delay)
	AttackCooldown int // Frames until can attack again
	JumpCooldown   int // Frames until can jump again

	// Idle patrol state
	IdleTimer       int // Frames spent in idle patrol
	PatrolDirection int // 1 = right, -1 = left, 0 = unset

	// Behavior tuning (set from config based on difficulty)
	ReactionDelay    int     // Frames to delay reactions
	AttackRange      float64 // Distance to start attacking
	RetreatThreshold float64 // Health % to start retreating
}

var Bot = donburi.NewComponentType[BotData]()
